FROM mysql:5.7.22

ENV MYSQL_ROOT_PASSWORD 5730477ee4a5a9048363e85aa0  
ENV MYSQL_DATABASE smartgardening   
ENV MYSQL_USER root  
ENV MYSQL_PASSWORD 5730477ee4a5a9048363e85aa0

ADD smartGardening.sql /docker-entrypoint-initdb.d